POST http://localhost:8080/api/register
Content-Type: application/x-www-form-urlencoded
Accept: */*

email=yohan.boichut@gmail.com&nom=Boichut&prenom=Yohan&password=babar

###



POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "yohan.boichut@gmail.com",
  "password": "babar"
}

###



GET http://localhost:8080/api/yeahh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoieW9oYW4uYm9pY2h1dEBnbWFpbC5jb20iLCJleHAiOjE2ODAxNjI3OTUsImlhdCI6MTY4MDEyNjc5NSwic2NvcGUiOiIifQ.OEMbroky1E6aKL2UHLtHdNvA9JCT7FuzMOODULtz81I

